### ISSUE TITLE
Double Tap

### ISSUE THREAD

**Issue by aravindkoneru** [aravindkoneru/FTC_9042#1]
On the latest commit, Tim said that an error was double tapping. Just to clarify, this means that the encoders do work, but the triggers are unreliable in the sense that the button constantly switch their function. One time right trigger may bring the arm in, and the next time it may push the arm out. We currently don't know the solution to the problem.

**Comment by TimMagoun** [comment]
The wishy washy ness of the encoder runmode seems to also appear in armDist.java. Still don't know why it is the case.

**Comment by aravindkoneru** [comment]
I added a class that basically does the same thing as armTester, but it uses buttons instead of encoders. This way we can be sure whether the problem lies with how we're handling the encoders or with how we're handling the triggers.

**Comment by aravindkoneru** [comment]
bump for tomorrow
